### ISSUE TITLE
error: unable to rename temporary 'Widget-9400721c.o.tmp' to output file 'Widget.o': 'No such file or directory'

### ISSUE THREAD

**Issue by yurivict** [sjaehn/BShapr#18]
Since the update to ```0.10``` build fails on some systems.

Log: http://package19.nyi.freebsd.org/data/122amd64-default-build-as-user/565366/logs/bshapr-lv2-0.10.log

**Comment by sjaehn** [comment]
Does it work with version >= 0.11? Release 0.10 was hungry for the newest gcc/clang. But clang 10 should be fine. In theory.

But the error looks like the result of something else. Once again parallel `make` (see #19) ? Finally fixed in 84f48616f92a32740fd59150f449c966935bd7a0 . Otherwise I've no idea.

**Comment by yurivict** [comment]
0.11 still has this problem.

You should use cmake or meson to avoid such problems.

**Comment by sjaehn** [comment]
The output part 
```
Build BShapr.lv2 DSP...Build BShapr.lv2 GUI...
``` 
really looks like parallel `make`. What about the latest master?

**Comment by sjaehn** [comment]
Blocking parallel make is now in v0.12 .
